name: wms_mobile
description: "Warehouse Management System Mobile App"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core Dependencies
  dio: ^5.3.2
  provider: ^6.0.5
  go_router: ^16.0.0
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0
  flutter_secure_storage: ^10.0.0-beta.4
  shared_preferences: ^2.2.2

  # Platform Integration
  permission_handler: ^12.0.1
  device_info_plus: ^11.5.0
  connectivity_plus: ^6.1.4
  package_info_plus: ^8.3.0
  path_provider: ^2.1.1

  # Scanning & Camera
  mobile_scanner: ^7.0.1
  camera: ^0.11.2
  image_picker: ^1.0.4

  # Thermal Printing
  print_bluetooth_thermal: ^1.1.4
  esc_pos_utils_plus: ^2.0.4

  # Serialization & UI
  json_annotation: ^4.8.1
  flex_color_scheme: ^8.2.0
  google_fonts: ^6.1.0
  intl: ^0.20.2
  image: ^4.0.17
  path: ^1.8.3
  photo_view: ^0.15.0
  nanoid2: ^2.0.1

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # Code generation and linting
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^6.0.0

  # Testing Infrastructure
  mockito: ^5.4.2
  http_mock_adapter: ^0.6.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/

  # Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
